### ISSUE TITLE
海外類似サービス

### ISSUE THREAD

**Issue by Hozum** [sikmi/shigoto-connect#103]

**Comment by n-keito** [comment]
海外クラウドソーシングの記事（1年前）
http://jp.techcrunch.com/2014/04/07/crowdsourcing-trend/
(3年前)
http://zenstartup.jp/2011/04/17/52/

million you
ポーランドのクリエイターのクラウドソーシングサービス。
約27000人のプロアマ含むクリエイターが所属してる。
数百人の選ばれたクリエーターはCreative Hub Groupというのに所属され、チームで問題解決をしてくれる。ブランド企業が抱える問題をMillion Youに送り、それを選ばれたクリエイター達と改善策を練る。その問題解決はタスク形式で行われ、コミュニティ内で動画、イラスト等の形で提案される。プロジェクトごとに選ばれたプロのクリエイター達がチームでアイデアを生み出していき、そのアイデアはMillion Youにより精査され、分析され、クライアントとともに最も良いものが選ばれる。最終的にプロジェクトに関わった全てのクリエイターに報酬が支払われる。

Design Crowd
デザインのコンペ形式。基本は変わらないけど、ジャンルごとにデザイナーがランキングされている。ランクや過去の作品から直接発注可能。プロジェクトのコンペに正体もできる。
クライアントはパッケージを購入する形で仕事を依頼し、最低150ドルから始まり全4種類。
高額なほどデザイナーの数が多くオプションも多い。
選ばれたデザイナーだけではなく、２,３位にも報酬があり参加証もあるらしい。また使用されなかったデザインは別サービスで販売することが可能となっている。
クライアント側は良いデザインがなければdesigncrowdに連絡すればデザイナーを増やしてくれるが、それでも気に入らなければ60日以内の全額返金可能。

freelancer
小規模のものを発注するならばココらしい。ジャンルが網羅されているイメージ。
総合型のためあまり他と差はないっぽい。強いて言うなら月額課金制を4種類設定していて、（月5,10,25,200$）高いほど手数料が安くなったり発注できる仕事の件数が多くなるなどの利点がある。

crowdflower
judgementと呼ばれるカテゴリが強いらしい。要するに人間の判断を要する仕事。
例えば画像の仕分け、不適切コメントの削除、レシートのデータ入力などなど。
システムに関しての特徴は記述なし。

Guru
ワークルームを作成してフリーランサーと作業を行う。契約であったりマイルストーンやタスクの作成をguruで行ってくれる。全て作業はguru上で。

chaordix

**Comment by n-keito** [comment]
Reddit

2014年に実験として新サービスをローンチしたが、半年でサービス終了。
コミュニティーによってプロジェクトをうまく操業する方法や、利用者からライセンスやプロ駄句をのリクエストを受ける方法、社内のプロセスを改善する方法を学んだ。
2015年、redditに改めて注力し直したが、サービスの継続が叶わなかった。

→クラウドファンディングのサービスでした　笑


WegoLook
http://blogos.com/article/79282/

ECサイトが正規なのか不安　→　誰かに確認してもらおう。
欲しいと思ってたプロジェクタをebayで手頃な価格という理由で購入を申し込んだが、実在するか不安。結果、売り手の人の近所に住む友人に商品の状態を確認してもらい、状態が良いという事で安心感を得た。
この体験から代理で出かけて商品を確認するサービスを提供しようという話になりサービス設立

1. 顧客が検査して欲しい作業を指定して投稿
2. wegolookが検査人（クラウドソーシング）を現場に派遣。要求された作業を実行。
3. 検査結果をもとに報告書を作成し顧客に提出

標準価格は59ドル。報告まで約2,3日。

依頼は購入希望のものではなく、土地、建造物、人などもおk。
最多依頼件数は車、重機

夫の墓がきちんと管理されているか確認や出会い系で知り合った人と実際に会う価値があるか確認する用途もあるらしい。


TaskRabbit (3年前米国ではやったそう)
http://diamond.jp/articles/-/14598
ちょっとした仕事を頼むクラウドソーシングサイト
仕事内容を掲載すると、登録会員が入札し、金額の最も低かった会員が仕事を請け負う。
仕事掲載料は無料。仕事した会員に支払われる金額の約15%が課金されるのみ。

依頼する事は誰でもできるが、仕事をする人は登録申請書を提出し、身元調査を受け、さらにオンラインでのトレーニングを受けなければならない。
これが、依頼人に安全を守るとともにTaskRabbitの信用につながっている。

仕事内容は買い物代行、寄付用の物品運搬、送迎や配達などから引越手伝、家事全般、家具の組み立て、車の修理など多種多様。ホームページを見るとバーテンディングや調理などもあったw
評価制度も存在し、依頼側はプロフィールから直接依頼も可能。


Handybook　http://techable.jp/archives/15625
掃除、家具の組み立て、家電修理、ペンキ塗りなど住まいに関する専門業者を手軽に派遣してもらえるアプリ。
人気の背景はアプリによる予約の手軽さと最短で翌日に派遣されるスピード感。
サービスを提供する人は経験、社交性、経歴などから「プロ」と判断された人だけ登録できる。
依頼者はアプリでジャンルと空き状況をチェックして予約するだけ。

クラウドソーシングにおける労働者のモチベーションに関する考察
http://www.crowdsourcing.org/document/worker-motivation-in-crowdsourcing--a-study-on-mechanical-turk/5049
ようやく
クラウドソーシング市場におけるクリエイターに対する報酬はハイスペックな人材を含むものの全体でみると非常に低い。クリエイターのモチベーションに関する既存の調査は参考にならないものが多く、モチベーションの理論が確立されていない。
したがって、既存のモチベーション理論とは違ったモデルを適用した。
モデルの調査はAmazon mechanical turkの431人のクリエイターより行った。
結果、ペイオフといった外部要因はクラウドソーシングのプラットフォーム利用に強く影響を及ぼす一方で、多くのクリエイターにとって「タスクの自律性」「スキルの多様性」といった喜びベースの感情による内的要因の要素が大きい事が判明した。

ペイオフ→ゲーム理論用語。自分のプレーから生まれる見返り報酬、利益。
タスクの自律性→恐らく仕事を任せられる事による承認欲求、役に立ってる達成感みたいな意味
スキルの多様性→特定の仕事を達成するのに必要なスキルの範囲。色んな仕事ができる喜びみたいな感じかと。

クリエイターのモチベーションで分類された、週の労働時間を横軸に、サンプル数を縦軸におかれたグラフも。

**Comment by n-keito** [comment]
![2015-05-24 20 56 26](https://cloud.githubusercontent.com/assets/8471636/7787746/69fd2330-0257-11e5-904f-3cc78ad35229.png)

**Comment by n-keito** [comment]
![2015-05-24 20 57 34](https://cloud.githubusercontent.com/assets/8471636/7787752/98b8c1de-0257-11e5-989d-e831db238133.png)
