### ISSUE TITLE
原稿作成

### ISSUE THREAD

**Issue by Hozum** [sikmi/shigoto-connect#128]

**Comment by yuutabuchi** [comment]
https://docs.google.com/document/d/1QKjGwh3I9BVfwVlkCzW_ckW0mpYokuHiBnh3Q-_5R2U/edit

**Comment by yuutabuchi** [comment]
全体のフローチャートはこちら
https://docs.google.com/drawings/d/1sOIJARTErxVD-BSi54m2rxE-3iO8mxwVw20CM7TEzAY/edit
