### ISSUE TITLE
Gitlab改修MTG

### ISSUE THREAD

**Issue by Hozum** [sikmi/shigoto-connect#136]
車、穂積、大内

**Comment by kuruma-gs** [comment]
# メニュー
- 不要なものはカットしたり、入れ子にしたりして隠す
  - 貫通系機能は入れ子にして隠し目にする
  - グループはあまり使わないので、切り替える感をもたせて右上などに移動
  - 左メニュー
    ダッシュボード階層の左メニューは不要
    プロジェクト階層の左メニューはそのまま
  
  - 上メニュー
    - プロフィールセッティングボタンはなどは不要そう
    - スニペット・Explore・new Projectもいらない
    - Searchも微妙かも
    
  - グループ
    - 存在自体をもう少し控えめに
  
# ダッシュボード
- プロジェクト選択を中心に

# プロジェクト
- オーナー向けページを作成
- Issueのステータスを4つにする
- Issue詳細をステータスごとにボタンの出しわけ
- デザイナーが納品しやすいようにファイル一覧を作る


# 今後のアクション
1. 登録導線・初期導線を作る
  目次出しだけ車作って、穂積レビュー（メモレベルでOK）
2. 上記を反映したパターンのGitlabワイヤーを引く
  とりあえずダッシュボードページを作る 日曜日に
3. 発注導線を作る
