### ISSUE TITLE
継続調査

### ISSUE THREAD

**Issue by Hozum** [sikmi/shigoto-connect#140]

**Comment by n-keito** [comment]
WeGoLook
http://www.prweb.com/releases/tradeshows/wegolook/prweb12483407.htm
トレードショーへのエージェント派遣サービスを開始した。写真やデータ集め、ミーティングやtレーニングへの参加も行ってもらえる。
顧客はエージェントから回収してほしい情報を詳細に示す必要がある。
情報収集が終われば、アプリに報告書を記入して終わり。

freelancer.com
フリーランサーを通して行われた仕事を分析し、今もっとも急速に成長しているスキルのカテゴリの一部をインフォグラフィックで示した。
ちなみに、ユーザーの74%が18〜34歳であるらしい。
2013年との比較が行われている。


クラウドソーシングを利用する際のリスクを減らす方法。
http://www.crowdsourcing.org/editorial/using-quality-assurance-mechanisms-to-ensure-accuracy-in-crowdsourcing/49546

要約
Q「クラウドソーシングのワーカーってちゃんと仕事してくれるの？○○な変な人いたらやだな〜。」
A「同じ仕事を独立して何人かに任せてチェックさせたり、プロジェクトを各タスクに細分化して割り振ればリスク減らせるよ。」

※あまり目新しい方法が書いてあるわけではありませんでした。


クラウドソーシングは多くの会社で有用なツールだが、利用するにあたって仕事の質に責任を持たなければならない。
これは切っても切り離せない問題。
企業は任せた大量の仕事をどのようにチェックしていけば良いのか？
スキルのない人に頼ったデータやタスクをまとめる際には多くの問題が生じる可能性がある。
例えば、
・ぼっちワーカーは知識に限度があり、タスクをこなすキャパをもっていないかも
・より早く簡単に報酬を得るために適当にサービスを利用する無責任ワーカーがいるかも
・間違った情報を故意に企業に提供する悪意あるユーザーがいるかも
・上記とは違ってユーザーが単純に間違いを犯すかも。

これらのリスクを低減させる品質保証の手段がいくつかある。
手段は二種類。(manual)マニュアルによる方法と(Algorithm)アルゴリズムによる方法
（）

マニュアルによる方法
より高いレベルの結果を保証する方法として、2人以上が独立して仕事を行い、その後お互いに結果を確認し合うこと。
他にも、信頼の置ける専門家のような人によって結果をレビューしてもらう方法もある。
発展的な方法として、それぞれの仕事をそれぞれのワーカーがレビューし合う作業モデルが考えられる。

アルゴリズムによる方法
プロジェクトを進行させるにあたって、ワーカーのスキルレベルをフィルタ分けし、精度をチェックし、タスクの複雑さを軽減させるアルゴリズムが必要。
多くのプロジェクトの進め方は、タスクがワークフローに挿入される方法を利用している。
各チェックポイントをワーカーが追うという方法は、プロジェクトを故意に妨害していないか、適当に仕事しようとしてないか、をふるう良い方法。そのような望ましくないワーカーはプロジェクトから追い出すことができる。
逆に、単にミスを犯してしまったワーカーには失敗を取り戻すチャンスを与えることができる。
また、タスクを明確にすることで、プロジェクトが始まる前に仕事の重複などの問題を自動的に判別することができ、ワークフローのプロセスを改善し、仕事の成果を出しやすくすることもできる。

また、ワーカーと仕事していく中で、ワーカーについて知ることで、プロジェクトのどこを任せられるのか識別できるようになる。そうすることによって、ワークフローの効率性及びプロジェクトの質を高めることができる。

Prequalification Testで専門的な作業に対して適切なスキルを持つ人を決定するのも良い方法。要するにこの人スキルあるの？ってのをテストする。

以上がプロジェクトの品質保証の方法だそう。

**Comment by n-keito** [comment]
![freelancer-ig](https://cloud.githubusercontent.com/assets/8471636/7897916/27514e94-072a-11e5-9550-292b71fa0663.jpg)

**Comment by n-keito** [comment]
クラウドソーシング

Innocentive
http://www.innocentive.com/
以前も軽く紹介しましたが、企業や政府、非営利団体などが報酬額と期限を明記して課題を投稿し、この課題に対してSolverが解決に取り組み、最良の解答に支払いが行われる問題解決型クラウドソーシング。
課題自体が高度なため期限は1,2ヶ月といったものが多いらしい。
報酬は数千から数万ドルとかなり高額。
ジャンルはビジネスから化学、数学、エンジニアリング、農業といった理系カテゴリが多め。

2011年の記事
「無印良品に学ぶクラウドソーシング」
http://www.president.co.jp/pre/backnumber/2011/20111017/20770/20779/

・「専門家は素人に負けない」という思い込みは捨てよ
　「特定少数の専門家」VS「不特定多数の素人」の構図を立てたときにどちらが製品開発において良い結果を出すのか。社内の専門家集団が勝つというのがメーカーの立場であるが、逆の事例も存在する。Innocentiveというサービスによって解決されている課題が存在する。Innocentiveでは約1/3の投稿が解決されているという研究があるらしい。

・多様性が能力に勝るための4つの条件
　不特定多数の素人集団が専門家集団を凌ぐという現象に対してペイジさんが説明しているのは、前人未到の高く険しい山を登る事に例えると、専門家集団はみんな同じ道を通って登頂しようとする。対して多様な素人集団は様々な方向、方法を使って登頂に挑戦する。結果として多様な集団の山頂に到達する確率は高くなる。といった感じ。

①問題が難しい
②問題を解決する人たちの視点や問題解決に使う思考手段が多様
③集団のメンバーは大きな集団の中から選ばれる事
④選ばれたメンバーの数が小さすぎない事

Innocentiveはペイジさんの理論を実践して証明した形になっている。
だとすれば、社外の多様で多数の消費者に製品開発に参加してもらえれば、社内の製品開発より良い成果を生むかもしれない

・ユーザーの知恵を製品開発に生かす良品計画の仕組み

無印良品はそうした取り組みを先駆けて行っていた。
http://www.muji.net/lab/
消費者が自分が欲しいと思う製品案を投稿したり、製品候補案に投票できるようにしている。製品化の決定も投票結果に愚直に従うという形にした。

これは、伝統的マーケティング調査とは少し異なっており、ニーズ情報のみではなくソリューション情報もユーザーから収集できる点、はるかに多様で多数のユーザーを対象に情報収集ができる点で異なっている。
こういったクラウドソーシングによる誰でもいつでも製品開発に参加できる仕組みによって社内専門家の能力を超えた新規性や独自性の高い製品開発につながっている。
さらに制作過程がオープン化され誰でも閲覧できるのもクラウドソーシングの特徴の一つ。

・開発過程のオープン化　にはプロモーション効果も
開発過程をオープンにすることで、開発製品の認知度が向上し、ユーザーの好意的態度の形成、当該製品の購入促進効果も期待できる。
ちなみにそうした製品を購入するかどうかはアイデア投稿者や製品指示投票者よりも開発過程を閲覧し続けるかによるそうで、メルマガなどで開発過程の全容の要約文の作成を行ったりして、閲覧者や閲覧量を増やす工夫を行っていた。

こうした取り組みによって、競合品に対する新規性、顧客ニーズの新規性でクラウドソーシングの方が高い成果を実現し、売り上げが取り組み初年度で約4倍になったそう。


アサインナビ
https://assign-navi.jp/

アサインナビ紹介記事
http://www.nikkei.com/article/DGXMZO85039340Q5A330C1000000/


去年東証マザーズに新規上場したリアルワールドの会員数が伸びているらしい
http://www.realworld.jp/crowd/

**Comment by n-keito** [comment]
idea connection
innocentiveと同じようなオープンイノベーションプラットフォーム。
報酬は2万〜１０万ドル。平均5万ドル。
働く手順は以下の通り、
機密保持：機密保持契約を結ぶ。全ての作業は各自で行う。
Client Agreement:仕事する間柄であるっていう契約を結ぶ。クライアントはサイトの知的所有権を共有(submit)し、Challenge Detail Document(以下CDD)を描く。
※CDDはIdeaConnection用語で、思いつきやデザインを具体化させることらしい。何かフレームワークがあるのかな？書類とかで。
解を得る：CDDの送付を終えるとクライアントは12週以内に最低一つの解案を提示する。
※期間のスタートはCCDを送付してソルバーがCCDを受け取ってから。
IP移行:ソルバーからの解案を受け取りは解の詳細や説明について詳しく書かれた文書で行われる。
支払い：もしクライアントが全ての解案をつっぱねたら、クライアントは報酬を支払う必要がない。もし解案から何か採用したら30日以内に報酬を支払う仕組み。
※つまりソルバーはタダ働きのリスクがある、しかも以前いったアイデアをもらうだけもらうっていう悪質なクライアントがいるかもしれない・・・。対策はしてるのか？？


Hypios
open problem solvingを円滑にするサービス。貢献者が特定のR&D問題を解決する。
Hypoisはコンサル会社ではない。個人はソルバーコミュニティに所属ができる。問題の意見を享受できる。参加者は機密保持契約を結ぶ。
そのソルバーコミュニティにR&Dの問題を共有することでクラウドソーシングによる問題解決へのアプローチができる。なんかサーチツールがあって、コミュニティ内で問題解決してくれそうな人を検索することができて、問題解決のコンペに招待することができる。Hypoisのシステムが勝手に関係ありそうな人をピックアップしてくれるらしい。
解案の一つを採用したかったら、お金を払ってその権利を買う流れらしい。
（話のつながりが急すぎ。検索後解案提示が複数くるまでの流れの記載なし。）

innoget
http://www.innoget.com/
オープンイノベーションマーケットプレイスというジャンルで、理系分野の知識や技術を売買するサイト。
目的はほかの人との共同研究だったり、研究の続きをしてくれる人探しだったり、技術の習得など。
サイト見た感じ値段は書いてない。連絡取る必要があるっぽい。
サイトの構成が学会っぽいので、論文がたくさん並んでるような感じ




ninesigma
http://www.ninesigma.co.jp/
日本支社があった。ただ募集中の案件をみるには大元サイトにて英語閲覧が必要。
成功事例もあってちょっとおもしろい。
オープンイノベーションの活用をサポートする会社なのだろうか。

TopCoder
http://jp.topcoder.com/
プログラミングコンテストとして有名だけど、クラウドソーシングもあるぽい。日本語あった。
http://itpro.nikkeibp.co.jp/atcl/column/14/346926/112800113/
HOME’Sが国内初でやった事例。
プログラマにコンペ形式、コンテスト形式で行ってもらうため、競争原理が働くとのこと。
最も良いものにしか報酬が支払われない。

製品アイデアをクラウドソーシングしてるサイト
Fiat Mio – create a car
BMW Customer Innovation Lab – in german
Kraft – innovate with Kraft
InnovationJam* – IBM’s idea generation project
Dell IdeaStorm – external idea sourcing
Betavine – Vodafone’s mobile app community
My Startbucks Idea – shaping the future of Starbucks
Ideasbrewery – Heineken Ideas Brewery
Connect + Develop – Innovation platform by P&G

フリーランスエンジニア向けビジネスマッチングサイトまとめ
https://biz.moneyforward.com/blog/business-hack/engineer-matching/
