### ISSUE TITLE
環境マップ（オーナー） / 市場分析

### ISSUE THREAD

**Issue by kuruma-gs** [sikmi/shigoto-connect#37]

**Comment by yuutabuchi** [comment]
https://docs.google.com/drawings/d/1yQKuBEnCDpOckxfn9Yf6NqFnci2qkJ--WUmU1lJPDoE/edit

**Comment by yuutabuchi** [comment]
https://github.com/sikmi/shigoto-connect/wiki/%E4%BC%81%E7%94%BB-%E7%92%B0%E5%A2%83%E3%83%9E%E3%83%83%E3%83%97-%E3%82%BD%E3%83%BC%E3%82%B9%E3%83%AA%E3%82%B9%E3%83%88
