### ISSUE TITLE
バズレポート

### ISSUE THREAD

**Issue by kuruma-gs** [sikmi/shigoto-connect#39]

**Comment by yuutabuchi** [comment]
# 目的: クラウドソーシングの利用者（ワーカー、発注者共に）にとっての利点や満足の点、逆に不満や不安な点、期待される改善点等を探ること
# 対象企業: クラウドソーシング全般に関するもの、クラウドワークス、ランサーズ、サグワークス、MUGENUP、gengo（※左から順に優先度が高いです。業界全般のものがわからなければ特にさくっと個別企業に移行してください。）
# 方法: 以下のツールやサービスを利用してください
- 公式ホームページのサービスカウンターに掲載された質問事項と回答
- サービス利用者のツイート内容
- 掲示板に掲載されている内容
# 期限: 月曜の勉強会後にその時点のアウトプットを出してください。水曜に全体にアウトプットを回覧させたいです。
# アウトプットイメージ: 次に添付します。社外秘でよろしく。なお、内容が分かればスクショベースでもテキストベースでも何でもいいです。
