### ISSUE TITLE
クラウドソーシングの成功・失敗レポート

### ISSUE THREAD

**Issue by kuruma-gs** [sikmi/shigoto-connect#40]

**Comment by n-keito** [comment]
クラウドソーシング
良い話
・自分にはスキルがないけど、替わりに請け負ってくれる。ブログの記事コンテンツをライターに依頼など。
・営業なしでクライアントに出会うことができるため、手軽にお願いできる。

ランサーズでロゴを募集してみた
http://info.ii-s.biz/2014/07/13/lancers_logo/
大人なのでお金で解決してみよう。作ったWebサービスへの投稿をクラウドソーシングで依頼してみる
前編
http://nakazye.hatenablog.com/entry/2014/11/14/003332
後編
http://nakazye.hatenablog.com/entry/2014/11/15/023934


悪い話
・ランサーズで仕事依頼のトラブル
ランサーズでHP作成を依頼しました。（プロジェクト形式）
先方評価は１００％、仕事件数も１００を超えています。

ところが、納期が遅れに遅れた挙句、見せていただいたHPは３分の１もできていないもの。
カートやボタンも使えず、修正依頼部分も未修正。
挙句さらに納期が遅れるそうです。

・広告デザイン依頼は結局広告の知識がない方に依頼することになる。ロゴならともっかく戦略的なデザインを行うことはできない。

・チラシデザインを依頼したものの、後日著作権の侵害で使用不可と某所から連絡が入る。ランサーずは著作権侵害のパクリが多すぎるらしい。

ランサーズの批評記事
http://kosuke.cc/column/impression-of-lancers/
ランサーズ社長の反応
http://www.web-20.net/2014/04/lancers_blog_owabi_setsumei.html
ランサーズのコピペライターとやり取りして運営に通報した結果
http://netbiju.net/out-sourcing/%E3%82%B3%E3%83%94%E3%83%9A%E3%83%A9%E3%82%A4%E3%82%BF%E3%83%BC/
クラウドソーシングでキャンセル前提の釣り依頼に引っかからない方法
http://hevohevo.hatenablog.com/entry/2014/04/24/181929




リモートワーク

最近始まったサービス
[ Remotty ]
http://www.sonicgarden.jp/20150416_remotty
リモートワークの本質（スライド）
https://prezi.com/2ck-pdvcuryn/presentation/

⚫︎日本ではリモートワークの普及がかなり難しそう
部分的にリモートワークを取り入れることはあっても、オフィス仕事の補完的な位置付けで1週間のほとんどを在宅で仕事するわけにはいかない。会議に出席するにはオフィスに行くしかなく、リモートワークを仕事の中心に据えるのは無理。

⚫︎日本の場合、リモートワークには大義名分が必要
家族が病気だとか考慮される事情がなければリモートワークをさせてもらえない。

⚫︎日本の残念な会社は結果よりも仕事への姿勢を評価しようとする
リモートワークとの相性は最悪

⚫︎リモートワークの導入には仕事するメンバー全員のコンセンサスの一致が必要不可欠
メンバー各自が自分の一番パフォーマンスの出しやすい働き方で働くのがチームにとって一番良いという同意がないと始まらない。
大企業で個人の意思に関係なく集められたチームには厳しい。

⚫︎リモートワークを普及させるには圧倒的な結果を見せつけること。
日本の会社でリモートワーク（在宅勤務）が普及しそうにない理由
http://dennou-kurage.hatenablog.com/entry/2014/01/28/205213



⚫︎良いところ
生産性が上がる。雨の中出勤して集中力を削ぎたくないなど

⚫︎よくないところ
コミュニケーション不足になりがち。

⚫︎リモートワークが主流になる。
理由は経営者にとっても従業員にとっても効率が良いから。通勤や職場環境に気を揉むなら家でやる方が捗る。今はビデオチャットやタスク管理などオンラインで共有できるので労働集約型である必要がない。オフィスは社員を監視する場でしかなくなってる。

リモートワークを開始して2年
http://www.huffingtonpost.jp/ryuichiro-toyoshi/remote-work_b_5615125.html


⚫︎在宅勤務は普段から家を出ないことが仕事
仕事での外出はおろか旅行へ行くなどの積極性を自分に求めることが困難になっていく。
自宅を働きやすい環境にしちゃうから、わざわざPC1台持って仕事なんてことはしなくなる

⚫︎罪悪感と暮らす
「人としての道徳観」に反していることを実感することが多くなってしまう。
自宅にいる＝仕事していないという罪悪感を感じてしまう

⚫︎完全なる成果主義
例えば今日デザインが仕上がってない＝さぼってる。
オフィスであればこいつは頑張ってたという評価にはなるが、リモートは結果至上主義。


「リモートワークは相当な覚悟がないと難しい」
http://xov.jp/e/119/








リモートワークの地味な知見
http://r7kamura.hatenablog.com/entry/2014/12/08/114141


週4日リモートワークで見えた世界
http://tech.grooves.com/entry/2015/03/12/135726



リモートワークはウチに合わない。実践した経営者が語る在宅勤務のデメリット
http://www.lifehacker.jp/2014/08/140818remote_work.html


リモートワークで感じた「今後の課題」
http://techblog.mindpl.co.jp/2014/08/remort_work_problem/







※おまけ
The Ultimate Guide to Remote Work
https://zapier.com/learn/the-ultimate-guide-to-remote-working/
